mysql:
  # 数据库登录用户
  username: miomio
  # 数据库密码
  password: 123321
  address: 127.0.0.1:3333
  # 数据库名字
  dbname: user-center
  timeout: 10s

gin:
  address: 127.0.0.1:90

redis:
  address: 127.0.0.1:6379