basePath: /api/v1
definitions:
  model.UserCreateReq:
    properties:
      account:
        type: string
      name:
        type: string
      password:
        type: string
      rePassword:
        type: string
    required:
    - account
    - name
    - password
    - rePassword
    type: object
  model.UserLoginReq:
    properties:
      account:
        type: string
      password:
        type: string
    required:
    - account
    - password
    type: object
  model.UserUpdatePwdReq:
    properties:
      account:
        type: string
      newPassword:
        type: string
      password:
        type: string
      rePassword:
        type: string
      userId:
        type: integer
    required:
    - account
    - newPassword
    - password
    - rePassword
    type: object
  model.UserUpdateReq:
    properties:
      name:
        type: string
      userId:
        type: integer
    required:
    - name
    - userId
    type: object
  util.Response:
    properties:
      code:
        type: integer
      data: {}
      message:
        type: string
    type: object
host: 127.0.0.1:8081
info:
  contact:
    name: miomiora
    url: https://github.com/miomiora
  description: Go Web 开发脚手架
  title: mio-init
  version: "1.0"
paths:
  /delete:
    get:
      consumes:
      - application/json
      parameters:
      - description: 用户令牌 Token 登录后产生
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.Response'
      security:
      - ApiKeyAuth: []
      summary: 删除用户
      tags:
      - 用户相关接口
  /list:
    get:
      consumes:
      - application/json
      parameters:
      - description: 用户令牌 Token 登录后产生
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.Response'
      security:
      - ApiKeyAuth: []
      summary: 用户列表
      tags:
      - 用户相关接口
  /user:
    get:
      consumes:
      - application/json
      parameters:
      - description: 用户令牌 Token 登录后产生
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.Response'
      security:
      - ApiKeyAuth: []
      summary: 获取用户信息
      tags:
      - 用户相关接口
  /user/get/my:
    get:
      consumes:
      - application/json
      parameters:
      - description: 用户令牌 Token 登录后产生
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.Response'
      security:
      - ApiKeyAuth: []
      summary: 用户信息
      tags:
      - 用户相关接口
  /user/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: 登录参数
        in: body
        name: object
        required: true
        schema:
          $ref: '#/definitions/model.UserLoginReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.Response'
      security:
      - ApiKeyAuth: []
      summary: 用户登录
      tags:
      - 用户相关接口
  /user/logout:
    post:
      consumes:
      - application/json
      parameters:
      - description: 用户令牌 Token 登录后产生
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.Response'
      security:
      - ApiKeyAuth: []
      summary: 用户登出
      tags:
      - 用户相关接口
  /user/register:
    post:
      consumes:
      - application/json
      parameters:
      - description: 注册参数
        in: body
        name: object
        required: true
        schema:
          $ref: '#/definitions/model.UserCreateReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.Response'
      security:
      - ApiKeyAuth: []
      summary: 用户注册
      tags:
      - 用户相关接口
  /user/update:
    post:
      consumes:
      - application/json
      parameters:
      - description: 用户令牌 Token 登录后产生
        in: header
        name: Authorization
        required: true
        type: string
      - description: 更新参数
        in: body
        name: object
        required: true
        schema:
          $ref: '#/definitions/model.UserUpdateReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.Response'
      security:
      - ApiKeyAuth: []
      summary: 修改用户信息
      tags:
      - 用户相关接口
  /user/update/pwd:
    post:
      consumes:
      - application/json
      parameters:
      - description: 用户令牌 Token 登录后产生
        in: header
        name: Authorization
        required: true
        type: string
      - description: 更新参数
        in: body
        name: object
        required: true
        schema:
          $ref: '#/definitions/model.UserUpdatePwdReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.Response'
      security:
      - ApiKeyAuth: []
      summary: 修改密码
      tags:
      - 用户相关接口
swagger: "2.0"
